blog/blog/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('martor/', include('martor.urls')),
]

blog/posts/urls.py
from django.urls import path

from posts import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('posts/category/<slug:slug>/', views.category_list, name='category_list'),
    path('posts/category/<slug:slug>/<int:post_id>/', views.post_detail, name='post_detail'),
]

blog/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

from martor.models import MartorField


User = get_user_model()


class Category(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    description = MartorField()

    def __str__(self) -> str:
        return f"{self.title}, slug - {self.slug}"


class Post(models.Model):
    title = models.CharField(max_length=255, blank=True)
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True,
    )
    text = MartorField()
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        related_name="posts",
        blank=True,
        null=True,
        verbose_name="Категория",
        help_text="Выбери категорию для поста"
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="posts",
        default=1
    )
    image = models.ImageField(
        upload_to="posts/",
        blank=True,
        null=True
    )

    class Meta:
        ordering = ("-pub_date",)

    def __str__(self) -> str:
        return f"{self.author} - {self.title}"

blog/posts/views.py
from django.conf import settings
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, render

from .models import Category, Post


def index(request):
    posts = Post.objects.select_related('category').all()
    paginator = Paginator(posts, settings.POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(
        request,
        'posts/index.html',
        {'page': page, 'paginator': paginator}
    )


def category_list(request, slug):
    category = get_object_or_404(Category, slug=slug)
    posts = category.posts.all()
    paginator = Paginator(posts, settings.POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)

    return render(
        request,
        'posts/category.html',
        {'category': category, 'page': page, 'paginator': paginator}
    )


def post_detail(request, slug, post_id):
    post = get_object_or_404(Post.objects.select_related('category'), id=post_id)
    return render(
        request,
        'posts/post_detail.html',
        {'post': post}
    )

blog/templates/base.html
{% load static %}
{% load martortags %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Титла{% endblock %}</title>
        <link href="{% static 'plugins/css/bootstrap.min.css' %}" type="text/css" media="all" rel="stylesheet" />
        <style>.main-container {margin-top: 3em}</style>
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
        {% block css %}{% endblock css %}
    </head>

    <body>
        {% include 'includes/header.html' %}
        <main>
            {% block content %}Контент{% endblock %}
        </main>
        {% include 'includes/footer.html' %}
        <script type="text/javascript" src="{% static 'plugins/js/jquery.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'plugins/js/bootstrap.min.js' %}"></script>
        {% block js %}{% endblock %}
    </body>
</html>

blog/templates/includes/footer.html
<footer class="footer">
    <div class="container">
        <div class="footer_inner">
            <div class="footer_inner_text">
                {% now "Y" %} год. Спасибо журналу "Код" за вдохновение
            </div>
        </div>
    </div>
</footer>

blog/templates/includes/header.html
{% load static %}
    <header class="header">
        <div class="container">
            <div class="header_inner">
                <div class="header-logo">
                    <a href="{% url 'posts:index' %}">
                        <img src="{% static 'img/logo.svg' %}">
                    </a>
                    <a class="header-logo-text" href="{% url 'posts:index' %}">milssky<br>workspace</a>
                </div>
                {% comment "right_block" %}
                <div class="header-right-block">
                    <ul class="header-menu">
                        <li>
                            <a href="">Первый</a>
                        </li>
                        <li>
                            <a href="">Второй</a>
                        </li>
                        <li>
                            <a href="">Третий</a>
                        </li>
                    </ul>
                </div>
                {% endcomment %}
            </div>
        </div>
    </header>

blog/templates/includes/post_item.html
{% load martortags %}

    <div class="post">
        <div class="post_header">
            <h1 class="post_title">
                {% if detail is not True %}
                    <a href="{% url 'posts:post_detail' post.category.slug post.id %}">{{ post.title }}</a>
                {% else %}
                    {{ post.title }}
                {% endif %}
            </h1>
            <div class="post_tags">
                <ul class="post_tag_list">
                    <a class="tag_url" href="{% url 'posts:category_list' post.category.slug %}"><li>{{ post.category.title }}</li></a>
                </ul>
            </div>
        </div>
        <div class="post_text">
            {{ post.text|safe_markdown }}
        </div>
        <div class="post_date">&#10002; {{ post.pub_date }}</div>
    </div>

blog/templates/posts/category.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link href="{% static 'plugins/css/ace.min.css' %}" type="text/css" media="all" rel="stylesheet" />
<link href="{% static 'martor/css/martor.bootstrap.min.css' %}" type="text/css" media="all" rel="stylesheet" />
{% endblock %}

{% block title %}{{ category.title }}{% endblock %}


{% block content %}
    <div class="container">
        {% for post in page %}
            {% include "includes/post_item.html" with post=post %}
        {% endfor %}
    </div>
{% endblock %}


{% block js %}
  <script type="text/javascript" src="{% static 'plugins/js/highlight.min.js' %}"></script>
  
  <script>
    $('pre').each(function(i, block){
        hljs.highlightBlock(block);
    });
  </script>
{% endblock %}

blog/templates/posts/index.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link href="{% static 'plugins/css/ace.min.css' %}" type="text/css" media="all" rel="stylesheet" />
<link href="{% static 'martor/css/martor.bootstrap.min.css' %}" type="text/css" media="all" rel="stylesheet" />
{% endblock %}

{% block title %}Главная{% endblock %}
{% block content %}
    <div class="container">
        {% for post in page %}
            {% include "includes/post_item.html" with post=post %}
        {% endfor %}
    </div>
{% endblock %}

{% block js %}
  <script type="text/javascript" src="{% static 'plugins/js/highlight.min.js' %}"></script>
  
  <script>
    $('pre').each(function(i, block){
        hljs.highlightBlock(block);
    });
  </script>
{% endblock %}

blog/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ post.title }}{% endblock %}
{% block content %}
    <div class="container">
        {% include "includes/post_item.html" with post=post detail=True %}
    </div>
{% endblock %}

{% block js %}
  <script type="text/javascript" src="{% static 'plugins/js/highlight.min.js' %}"></script>
  
  <script>
    $('pre').each(function(i, block){
        hljs.highlightBlock(block);
    });
  </script>
{% endblock %}